---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                           SAP Hostagent Install                            |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


# Steps
#   Create Temp Dir
#   Extract to Temp Dir
#   Execute saphostexec from Temp Dir

# - name:                                 Test
#   ansible.builtin.debug:
#     var:                                tmp_directory

- name:                                 "SAP Hostaget Install: -  Create temp directory"
  ansible.builtin.file:
    path:                               "{{ tmp_directory }}/saphostagent"
    state:                              directory
    mode:                               0755


# - name:                                 SAP Hostagent Install
#   ansible.builtin.debug:
#     msg:
#       - "SAP Hostagent Install"



# - name:                                 "SAP Hostaget Install: -  Remove temp directory"
#   ansible.builtin.file:
#     path:                               "{{ tmp_directory }}/saphostagent"
#     state:                              absent

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
