---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                           SAP Hostagent Install                            |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


# Steps
#   Temp Dir created by BOM
#   Extract to Temp Dir by BOM
#   Execute saphostexec from Temp Dir

# - name:                                 Test
#   ansible.builtin.debug:
#     var:                                tmp_directory
#     msg:
#       - "SAP Hostagent Install"

# - name:                                 "SAP Hostaget Install: -  Create temp directory"
#   ansible.builtin.file:
#     path:                               "{{ tmp_directory }}/saphostagent"
#     state:                              directory
#     mode:                               0755




- name:                                 "SAP Hostaget Install: SAP Hostaget Install on {{ ansible_hostname }}"
  ansible.builtin.shell: |
                                        ./saphostexec -install
  args:
    chdir:                              "{{ target_media_location }}/SAPHOSTAGENT"
    # creates:                            "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/sap_deployment_scs.txt"
  environment:
    # SAPSYSTEMNAME:                      "{{ sid_to_be_deployed.sid | upper }}"
    TMPDIR:                             "{{ tmp_directory }}/saphostagent"
  register:                             saphostagent_installation
  failed_when:                          saphostagent_installation.rc > 0














# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                                 Clean-up                                   |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                 "SAP Hostaget Install: -  Remove temp directory"
  ansible.builtin.file:
    path:                               "{{ target_media_location_windows }}/SAPHOSTAGENT"
    state:                              absent

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
