# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# -------------------------------------+---------------------------------------8
# scr_kernel_files_{{ scr_source_sid }}.files       (source)
# scr_kernel_files_{{ scr_dest_sid }}.files         (destination)
# source_root: /sapmnt/{{ scr_source_sid }}
# destination_root: /sapmnt/{{ scr_dest_sid }}

# TODO: 
#   If scr_kernel_files_{{ scr_source_sid }} or scr_kernel_files_{{ scr_dest_sid }} is not defined, it means the inventory step was skipped for that system. In this case, we should either:
#     - Load the inventory data from a previously saved location (if available) to allow the comparison to proceed without forcing the user to re-run the inventory step.
#     - Fail with a clear error message indicating that the inventory step must be completed before comparison.
#     - Or, optionally, trigger the inventory step for the missing system before proceeding with the comparison.
- name:                                 "Compare: Source file inventory"
  ansible.builtin.debug:
    msg:                                "{{ lookup('template', 'roles-scr/scr_kernel/templates/inventory_file_detail.j2') }}"
    verbosity:                          2
  vars:
    sapsid:                             "{{ scr_source_sid }}"

- name:                                 "Compare: Destination file inventory"
  ansible.builtin.debug:
    msg:                                "{{ lookup('template', 'roles-scr/scr_kernel/templates/inventory_file_detail.j2') }}"
    verbosity:                          2
  vars:
    sapsid:                             "{{ scr_dest_sid }}"


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                      Log: Starting SAP Kernel Compare                     |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- name:                                 "LOG - Starting SAP Kernel Compare"
  ansible.builtin.include_role:
    name:                               roles-scr/scr_log_function
  vars:
    activity:                           log_summary
    action:                             store
    payload:                    "Starting SAP Kernel Compare"

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Compute structural differences                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- name:                                 "Compare: Compute file sets" 
  delegate_to:                          localhost
  delegate_facts:                       true
  ansible.builtin.set_fact:
    scr_common_keys:                    "{{ _source_map.keys() |  intersect(_target_map.keys()) }}"
    scr_extra_on_target:                "{{ _target_map.keys() | difference(_source_map.keys()) }}"
    scr_missing_on_target:              "{{ _source_map.keys() | difference(_target_map.keys()) }}"
  tags:
    - silent_v1


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                                                                            |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
# Checksum comparison on common files
- name:                                 "Compare: Split common files by checksum"
  delegate_to:                          localhost
  delegate_facts:                       true
  ansible.builtin.set_fact:
    scr_matches:                        "{{ scr_matches | default([]) + ([item] if _source_map[item] == _target_map[item] else []) }}"
    scr_changed:                        "{{ scr_changed | default([]) + ([item] if _source_map[item] != _target_map[item] else []) }}"
  loop:                                 "{{ hostvars['localhost']['scr_common_keys'] }}"
  loop_control:
    label:                              "{{ item }}"
  # no_log:                               true
  tags:
    - silent_v1


- name:                                 "Compare: List - Matching files"
  ansible.builtin.debug:
    var:                                hostvars['localhost']['scr_matches']
    verbosity:                          2

- name:                                 "Compare: List - Changed files"
  ansible.builtin.debug:
    var:                                hostvars['localhost']['scr_changed']
    verbosity:                          2



# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                                                                            |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
# Consolidated listing (human‑readable)
- name:                                 "Compare: Build consolidated sync report"
  delegate_to:                          localhost
  delegate_facts:                       true
  ansible.builtin.set_fact:
    scr_sync_report: >-
      {{
        []
        + (hostvars['localhost']['scr_matches']           | map('regex_replace', '^(.*)$', 'MATCH...................  \1') | list)
        + (hostvars['localhost']['scr_missing_on_target'] | map('regex_replace', '^(.*)$', 'COPY_FROM_SOURCE........  \1') | list)
        + (hostvars['localhost']['scr_changed']           | map('regex_replace', '^(.*)$', 'OVERWRITE_FROM_SOURCE...  \1') | list)
        + (hostvars['localhost']['scr_extra_on_target']   | map('regex_replace', '^(.*)$', 'REMOVE_FROM_TARGET......  \1') | list)
      }}
  tags:
    - silent_v1

- name:                                 "Compare: Sync Report"
  ansible.builtin.debug:
    var:                                hostvars['localhost']['scr_sync_report']
    verbosity:                          0


# /*---------------------------------------------------------------------------8
# |                                                                            |
# | Store in object_store                                                      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- name:                                 "SCR: store compare data in object_store"
  ansible.builtin.include_role:
    name:                               roles-scr/scr_log_function
  vars:
    activity:                           object
    action:                             store
    payload:
                                        - scr_matches,           localhost
                                        - scr_missing_on_target, localhost
                                        - scr_changed,           localhost
                                        - scr_extra_on_target,   localhost


# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
...
